export type { AlumnoDTO } from './AlumnoDTO';
export type { LocalidadDTO } from './LocalidadDTO';
export type { ContactoEmergenciaDTO } from './ContactoEmergenciaDTO';
export type { FichaMedicaDTO } from './FichaMedicaDTO';
export type { ProfesorDTO } from './ProfesorDTO';
export type { RangoEtarioDTO } from './RangoEtarioDTO';
export type { ArticuloDTO } from './ArticuloDTO';
export type { TipoClaseDTO } from './TipoClaseDTO';
export type { InscripcionDTO } from './InscripcionDTO';
export { ModalType } from './ModalType'; 