export type { AlumnoDTO } from './AlumnoDTO';
export type { LocalidadDTO } from './LocalidadDTO';
export type { ContactoEmergenciaDTO } from './ContactoEmergenciaDTO';
export type { FichaMedicaDTO } from './FichaMedicaDTO';
export type { ProfesorDTO } from './ProfesorDTO';
export type { RangoEtarioDTO } from './RangoEtarioDTO';
export type { ArticuloDTO } from './ArticuloDTO';
export type { TipoClaseDTO } from './TipoClaseDTO';
export type { InscripcionDTO } from './InscripcionDTO';
export type { InscripcionProfesorDTO } from './InscripcionProfesorDTO';
export type { DiaDTO } from './DiaDTO';
export type { HorarioiDiaxTipoClaseDTO } from './HorarioiDiaxTipoClaseDTO';
export type { ConfHorarioTipoClaseDTO } from './ConfHorarioTipoClaseDTO';
export type { ClaseDTO } from './ClaseDTO';
export { ModalType } from './ModalType'; 